version: 2
updates:
- package-ecosystem: npm
  directory: "/site"
  schedule:
    interval: daily
    time: "16:00"
    timezone: America/Chicago
  open-pull-requests-limit: 10
  reviewers:
  - nakleiderer
  ignore:
  - dependency-name: gatsby
    versions:
    - ">= 2.13.11.a, < 2.13.12"
  - dependency-name: webpack
    versions:
    - 5.26.0
    - 5.34.0
    - 5.35.0
    - 5.36.0
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
  - dependency-name: firebase-tools
    versions:
    - 9.2.2
    - 9.3.0
    - 9.4.0
  - dependency-name: firebase
    versions:
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.5
    - 7.13.8
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
  - dependency-name: postcss
    versions:
    - 8.2.11
